### ISSUE TITLE
Not installable/updatable

### ISSUE THREAD

**Issue by RogueEntityX** [jbhaywood/foundryvtt-honeyheist#14]
Regarding v1.4 for Foundry v11. While you just updated it for compatibility, I believe you need to update its listing/page on foundryvtt.com. Currently, the system does not show up in the System Installer in the Foundry app, nor can it be updated from an earlier version. More info here: https://discord.com/channels/170995199584108546/701846414208008302/1160925958585462894

**Comment by taedison** [comment]
yeah, currently you can't install it on v11 or on v10

**Comment by jbhaywood** [comment]
I made a change to the config. Try again and let me know if it works now.

**Comment by taedison** [comment]
Yes, I can install it now on v10 and v11. Thank you!

Only thing not working right now is, installing it on forge-vtt.com, though that might be just because there was no new release version, their system did not update their version.

**Comment by RogueEntityX** [comment]
Likewise, I can install on V11 now. I did have to uninstall the v1.24 I had, though; could not update directly.

**Comment by rikmarais** [comment]
Hey there, Phi from Forge here
> Only thing not working right now is, installing it on forge-vtt.com, though that might be just because there was no new release version, their system did not update their version.

@taedison is right, since the Bazaar considers versions immutable, it won't see a difference between v1.4 before and after the changes.

@jbhaywood could I please request a version bump of the release 🙏 That would let downstream (like the Bazaar and any other users who  didn't retry v1.4 since the original release) get the new version

In the mean time if you encounter that you can't install v1.4 on Forge, please install it as a custom module from Manifest URL (untick the `Install from the Bazaar` option)

![image](https://github.com/jbhaywood/foundryvtt-honeyheist/assets/34374883/592a0bc7-8efc-4999-8665-d0219fd4eb2e)

**Comment by jbhaywood** [comment]
I updated it to v1.5. Let me know if that doesn't fix it for the Forge.

**Comment by rikmarais** [comment]
That's solved it, thanks so much!
